### ISSUE TITLE
Suggestion: Hide SCM password during deployment

### ISSUE THREAD

**Issue by gavvvr** [thomis/eventhub-command#4]
This is the suggestion to hide SCM password from stdout during deployment. For now every command executed on remote servers gets printed to stdout 'as is'

**Comment by thomis** [comment]
Hi @gavvvr 
Password is now filtered in the output. Please try with version 0.10.0 and let me know if this is fine.
Best
Thomi

**Comment by gavvvr** [comment]
Hi @thomis 
Thanks! The SCM password is `[FILTERED]` now in the output
